permalink:           pretty


# Setup
title:               COVID-19  
tagline:             'A Pandemic Journal'
description:         'A person journal documenting the COVID-19 pandemic.'
url:                 http://gruchalla.github.io
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Kenny Gruchalla, Ph.D.
  url:               https://gruchalla.github.io

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]